pipeline:
  docker:
    image: plugins/docker
    repo: registry.tstllc.net/llisk/alpine-haproxy
    force_tag: true

publish:
  docker:
    repo: registry.tstllc.net/llisk/alpine-haproxy
    tag:
      - latest
    when:
      branch:
        include: [ master, release/* ]

publish:
  docker:
    repo: registry.tstllc.net/llisk/alpine-haproxy
    tag:
      - ${DRONE_BRANCH}-latest
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        exclude: [ master ]
